### ISSUE TITLE
Newborn Care Corrections_Julia_February

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#48]
(All page numbers refer to new, .md edition)
13: Introduction: Incorrect heading hierarchy: “Updating the course material”
46: 1-g: Incorrect numbering Figures 1-A - 1-J (re renumbering sheet)
58: 2. Incorrect heading hierarchy: “Assessing an infant’s gestational age at birth”. Is currently a bullet point under “Objectives. Needs to be its own heading.
117: Table 3-1 Missing last two rows: “Hips”
139: 4-37: Incorrect heading hierarchy: “The baby friendly initiative” 
185: 6-17: Incorrect heading hierarchy: “Milk feeds for sick or high-risk infants”
379: 12-35: Incorrect heading hierarchy: “Chronic intra-uterine infection” currently plain text, needs to be `###`
406: Case Study 3: Missing letter, question 1 answer: “...caused by”
409: 14. Incorrect heading hierarchy: “Introduction to birth defects”. Is currently a bullet point under “Objectives. Needs to be its own heading.

**Comment by arthurattwell** [comment]
I've made these correx. Julia, you can check on our staging site electricbookworks.github.io/bettercare/ for now, though final check must be on print PDF (which I must still create).

**Comment by julianorrish** [comment]
Looks good to me @arthurattwell! Just the images and table that I obviously cannot double check at the moment, but will see those in the final print PDF?

**Comment by arthurattwell** [comment]
Thanks. You'll find the table here: http://electricbookworks.github.io/bettercare/newborn-care/3A.html#h-guidelines-for-a-detailed-examination

I must get you a PDF to check before we close this issue. Assigning back to me for that.

**Comment by julianorrish** [comment]
Perfect. Table is now correct too.

On Mon, Feb 9, 2015 at 4:40 PM, Arthur Attwell notifications@github.com
wrote:

> Thanks. You'll find the table here:
> http://electricbookworks.github.io/bettercare/newborn-care/3A.html#h-guidelines-for-a-detailed-examination
> 
> I must get you a PDF to check before we close this issue. Assigning back
> to me for that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/48#issuecomment-73518788
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
PDF ready for @julianorrish to check:

`Dropbox (Electric Book Works)\bettercare\courses-professional\newborn-care\setting\proofs\for-checking`

**Comment by julianorrish** [comment]
@arthurattwell: Figures 2A-2 and 2A-3 could ideally be on one page.
Otherwise the rest look perfect - some even better than in the original!

On Wed, Feb 25, 2015 at 10:52 AM, Arthur Attwell notifications@github.com
wrote:

> Assigned #48 https://github.com/electricbookworks/bettercare/issues/48
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/48#event-241551267
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
Yeah, I wondered about that but thought the type would get too small to read easily. All good.
