### ISSUE TITLE
Well Women Corrections_Julia_February

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#49]
(All page numbers refer to new, .md edition)
13: Introduction: Incorrect heading hierarchy: “Updating the Course Material”
17: 1-6: Incorrect formatting, should be in a bubble: “Breast and cervical cancer can be cured if detected early and treated correctly”
18: 1-8: Incorrect formatting, should be in a bubble: “Breast cancer may present with a new lump, any change in an old lump, or nipple discharge.”
75: 3-19: Incorrect formatting, should be in a bubble: “The discharge of bacterial vaginosis has a fishy smell”
80: 3-30: Incorrect formatting, should be in a bubble: “A positive VDRL text suggests syphilis.”
110: Incorrect numbering: 1 should be 3

**Comment by arthurattwell** [comment]
Correx done on staging http://electricbookworks.github.io/bettercare/. Over to @julianorrish to check.

**Comment by julianorrish** [comment]
All checked, all good @arthurattwell
