### ISSUE TITLE
Saving Mothers and Babies Corrections_Julia_February 2015

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#50]
(All page numbers refer to new, .md edition)
13: Introduction:  Incorrect heading hierarchy, “Updating the Course Material”
16: 1-2:  Incorrect formatting, should be in a bubble: The mortality rate is the proportion of people who have died.”
21: 1-21: Incorrect heading hierarchy “What are the important steps of a mortality audit?”
22: 1-25: Incorrect formatting, should be in a bubble: “Plans to improve patient care is based on the mortality report.”
28: 1-44: Missing: Calculation for “low birth weight rate”
36: 2-2: Missing: Calculations for “Maternal Mortality Ratio” and “Maternal Mortality Ratio”
41: 2-18: Missing numbering: “1. Non-pregnancy…2. Pre-existing…”
51: 2-42: Missing: Calculation for “Maternal Mortality Index”
62: 3-3 Delete: “?” in practical lesson bubble:  
63: 3-5: Missing: Calculations for “Perinatal mortality rate” and nd example of a calculation for the “perinatal mortality rate”
70: 3-24: Missing: Calculation for “stillbirth rate”
71: 3-27: Delete “?” in heading between South and Africa
75: 3-39: Missing: Calculation for “neonatal mortality rate”
81: 3-54: Missing: Calculation for “perinatal care index”
96: 4-22: Spelling: “mortality”, not “morality” in the article heading. Insert “t”

**Comment by arthurattwell** [comment]
These correx are made and ready for checking, @julianorrish http://electricbookworks.github.io/bettercare/saving-mothers-and-babies/

**Comment by julianorrish** [comment]
All checked.

On Mon, Feb 9, 2015 at 5:06 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #50 https://github.com/electricbookworks/bettercare/issues/50
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/50#event-232511252
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com
