### ISSUE TITLE
Mother and Baby Friendly Care Corrections_Julia_February 2015

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#51]
(All page numbers refer to new, .md edition)
13: Introduction: incorrect heading hierarchy: “Updating the course material”
85: 4-12: Insert figure 4-1
86: 4-13: Insert figure 4-2
102: 4. Case Study 4: Incorrect heading hierarchy, should be a new question
112: 5-25: Spelling error: “simple” should be “simply”
130: 5. Case Study 3: Incorrect heading hierarchy, question 4.1 should be a new question in bold and following numbers to be renumbered 1 - 6

---

**Comment by arthurattwell** [comment]
Correx done, ready for @julianorrish to check on http://electricbookworks.github.io/bettercare/mother-and-baby-friendly-care/

Images to come -- then we'll output PDF for final checking.

**Comment by julianorrish** [comment]
All good. Now just need to check images in final PDF

**Comment by arthurattwell** [comment]
I'll create a PDF when the images are in.

**Comment by arthurattwell** [comment]
PDF ready for @julianorrish to check.

`Dropbox (Electric Book Works)\bettercare\courses-professional\mother-and-baby-friendly-care\proofs`

**Comment by julianorrish** [comment]
@arthurattwell Images look great as is

On Tue, Feb 24, 2015 at 4:08 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #51 https://github.com/electricbookworks/bettercare/issues/51
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/51#event-240922023
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com
