### ISSUE TITLE
Perinatal HIV Corrections_Julia_February

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#53]
(All page numbers refer to new, .md edition)
13: Introduction: incorrect heading hierarchy: “Updating the course material”
21: 1-12: Incorrect formatting, should be in a bubble: “A positive PCR test in an infant indicates that the infant is infected with HIV”
115: 5-10: Incorrect formatting for “2. Empowering people”

**Comment by arthurattwell** [comment]
Correx done, over to @julianorrish for checking. http://electricbookworks.github.io/bettercare/perinatal-hiv/

**Comment by julianorrish** [comment]
Corrections all checked and all correct.

On Mon, Feb 9, 2015 at 5:13 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #53 https://github.com/electricbookworks/bettercare/issues/53
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/53#event-232516641
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com
