### ISSUE TITLE
Childhood TB Corrections_Julia_February 2015

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#54]
(All page numbers refer to new, .md edition)
4: Acknowledgements: Missing images/logos for Desmond Tutu TB Centre and TBCTA
14: Introduction: incorrect heading hierarchy: “Updating the course material”
48: 3-6: Incorrect formatting: Numbers should be in a list format
76: 4-32:  Incorrect formatting, should be in a bubble: “Drug resistance is becoming a major problem in South Africa.”

**Comment by arthurattwell** [comment]
Correx done on staging web version. 

http://electricbookworks.github.io/bettercare/childhood-tb/

Note image section at the back still to be added, and checked on PDF after images are in.

**Comment by julianorrish** [comment]
All corrected!

On Tue, Feb 10, 2015 at 10:48 AM, Arthur Attwell notifications@github.com
wrote:

> Correx done on staging web version.
> 
> http://electricbookworks.github.io/bettercare/childhood-tb/
> 
> Note image section at the back still to be added, and checked on PDF after
> images are in.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/54#issuecomment-73663910
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
Thanks. I'll create a PDF when the images are in.

**Comment by arthurattwell** [comment]
PDF ready for @julianorrish to check.

`Dropbox (Electric Book Works)\bettercare\courses-professional\childhood-tb\setting\proofs`

**Comment by julianorrish** [comment]
@arthurattwell Checking of images done and issues/suggestions noted and
highlighted on the google sheet for images:
https://docs.google.com/a/electricbookworks.com/spreadsheets/d/1kC6kR6ksXvc5NKffANbCQsshcEmRsi_zxbut7x7655A/edit#gid=0

On Tue, Feb 24, 2015 at 1:30 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #54 https://github.com/electricbookworks/bettercare/issues/54
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/54#event-240840153
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
New PDF done, all fine I think.

@julianorrish check if you're curious, but not crucial -- closing this issue.
