### ISSUE TITLE
Maternal Care Corrections_Julia_February 2015

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#56]
(All page numbers refer to new, .md edition)
16: Introduction: incorrect heading hierarchy: “Updating the course material”
68: 1B, I: incorrect heading hierarchy: “I. Special points about the palpation of the fetus”
70: 1B, M: Incorrect heading hierarchy: “M. Listening to the fetal heart”
71: 1B, O.: Incorrect heading hierarchy: “O. Assessment of the state of fetal wellbeing”
90: 1F, G: Spelling: …(push her hands towards each other)...
109: 2-40: Incorrect heading hierarchy: “2-40 What are the aims of fetal resuscitation”
119: 2A, H: Incorrect heading hierarchy: “H. Recording the presenting part and the amount of fetal head palpable above the brim of the pelvis”
119: 2A, I: Incorrect heading hierarchy: “I. Writing notes on the antenatal record card”
137: 3-37: Incorrect heading hierarchy: "Gestational hypertension" - should be the same as "Chronic hypertension" a few articles later

**Comment by arthurattwell** [comment]
Done, ready for @julianorrish to check staging:

http://electricbookworks.github.io/bettercare/maternal-care/0-3-contents.html

Then we'll check PDF when images are in.

**Comment by julianorrish** [comment]
Corrections are all right.

On Tue, Feb 10, 2015 at 12:49 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #56 https://github.com/electricbookworks/bettercare/issues/56
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/56#event-233115371
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
Thanks. I'll create a PDF for final checking when the images are in.

**Comment by arthurattwell** [comment]
PDF ready for @julianorrish to check.

`Dropbox (Electric Book Works)\bettercare\courses-professional\maternal-care\setting\proofs`

**Comment by julianorrish** [comment]
@arthurattwell Checking of images done and issues/suggestions noted and
highlighted on the google sheet for images:
https://docs.google.com/a/electricbookworks.com/spreadsheets/d/1kC6kR6ksXvc5NKffANbCQsshcEmRsi_zxbut7x7655A/edit#gid=0

On Mon, Feb 23, 2015 at 7:34 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #56 https://github.com/electricbookworks/bettercare/issues/56
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/56#event-240306436
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
New proofs in `Dropbox (Electric Book Works)\bettercare\courses-professional\maternal-care\setting\proofs`

@julianorrish do you want to have a quick look before I close this issue?

**Comment by julianorrish** [comment]
Sure thing

On Wed, Feb 25, 2015 at 5:05 PM, Arthur Attwell notifications@github.com
wrote:

> New proofs in Dropbox (Electric Book
> Works)\bettercare\courses-professional\maternal-care\setting\proofs
> 
> @julianorrish https://github.com/julianorrish do you want to have a
> quick look before I close this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/56#issuecomment-75975594
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by julianorrish** [comment]
Everything looks good @arthurattwell!

On Wed, Feb 25, 2015 at 5:08 PM, Julia Norrish julia@electricbookworks.com
wrote:

> Sure thing
> 
> On Wed, Feb 25, 2015 at 5:05 PM, Arthur Attwell notifications@github.com
> wrote:
> 
> > New proofs in Dropbox (Electric Book
> > Works)\bettercare\courses-professional\maternal-care\setting\proofs
> > 
> > @julianorrish https://github.com/julianorrish do you want to have a
> > quick look before I close this issue?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/electricbookworks/bettercare/issues/56#issuecomment-75975594
> > .
> 
> ## 
> 
> ## 
> 
> Kind regards
> 
> _Julia Norrish_
> 
> Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
> Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74 464
> 5588 | E: julia@electricbookworks.com | Website: www.electricbookworks.com

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com
