### ISSUE TITLE
Infection Prevention and Control Corrections_Julia_February

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#58]
(All page numbers refer to new, .md edition)
21: Introduction: incorrect heading hierarchy: “Updating the course material”
54: end of 2-13: Incorrect heading hierarchy: “Fungi, viruses and parasites” should be ## 
108: 4-16. Caption to Figure 4-3 shoul be “How to handrub” not “...hand wash”
144: “Figure 6-1” should be “Table 6-1” (therefore all following figures to be renumbered down one ie Figure 6-2 is now 6-1 and all following tables should be renumbered up one ie Table 6-1 is now 6-2)
159: Chapter 6, Case study 1, Question 2, last bullet point: “### 3….” Should be new question”
192: 8-15: Incorrect heading hierarchy, “Drug resistant tuberculosis” should be ##
Addendum missing

**Comment by julianorrish** [comment]
@arthurattwell, ready for implementation

**Comment by arthurattwell** [comment]
Correx done, @julianorrish to check on staging:

http://electricbookworks.github.io/bettercare/infection-prevention-and-control/

Then to check again when PDF with images available.

**Comment by julianorrish** [comment]
Everything looks good.

On Tue, Feb 10, 2015 at 12:04 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #58 https://github.com/electricbookworks/bettercare/issues/58
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/58#event-233090766
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
Thanks. I'll create a PDF for checking when images are in.

**Comment by arthurattwell** [comment]
PDF ready for @julianorrish to check.

`Dropbox (Electric Book Works)\bettercare\courses-professional\infection-prevention-and-control\setting\proofs`

**Comment by arthurattwell** [comment]
I need to work through the tables in this book: some should be created in HTML (not markdown).

**Comment by julianorrish** [comment]
Figures look really good in this one @arthurattwell

On Thu, Feb 26, 2015 at 11:50 PM, Arthur Attwell notifications@github.com
wrote:

> I need to work through the tables in this book: some should be created in
> HTML (not markdown).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/58#issuecomment-76281689
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
Tables fixed and layout tweaked. This one's ready to roll.
