### ISSUE TITLE
Intrapartum Care Corrections_Julia_February 2015

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#59]
(All page numbers refer to new, .md edition)
13: Intro: “Updating course material” should be ##
28: 1-39: “Assessing the urine” should be ## heading
78: 3A Skills: “M. Fetal heart rate pattern” should be ###
85: 3B Skills: After J., “Moulding” should be ## instead of a block quote.
177: 7-14: number is a duplicate (two 7-14s). Following article numbers to be updated.
178: 7-16: numbering skips from 7-16 to 7-20:  Following article numbers to be updated.

Tests and Answers:
The answers for Test 7 should read as follows: (updated article references)
1. b (7-2)
2. - 11. are correct
12. d (7-18)
13. Correct
14. a (7-26)
15. d (7-33)
16. c (7-35)
17. b (7-36)
18. a (7-38)
19. d (7-40)
20. a (7-43)

@arthurattwell  to update these article references

**Comment by julianorrish** [comment]
@arthurattwell  to implement corrections

**Comment by arthurattwell** [comment]
Thanks, @julianorrish. I've made the correx so you can check on staging:

http://electricbookworks.github.io/bettercare/intrapartum-care/

One more thing: since we've renumbered 7-14 to the end of 7, please can you go through the chapter test and answers for chapter 7 and update the article numbers given for each answer:

http://electricbookworks.github.io/bettercare/intrapartum-care/test-answers.html#test-7-the-puerperium

It's likely that in most cases you'll be subtracting 2 from each article number (e..g 7-18 becomes 7-16).

**Comment by julianorrish** [comment]
Checked initial corrections - all perfect.

Good point about the article references in the tests and answers. Will
check and update the issue.

Have updated the article references for the answers to the tests. @arthurattwell to implement

On Tue, Feb 10, 2015 at 3:34 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #59 https://github.com/electricbookworks/bettercare/issues/59
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/59#event-233199567
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
> The answers for Test 7 should read as follows: (updated article references)
> 1. b (7-2)
> 2. - 11. are correct
> 12. d (7-18)
> 13. Correct
> 14. a (7-26)
> 15. d (7-33)
> 16. c (7-35)
> 17. b (7-36)
> 18. a (7-38)
> 19. d (7-40)
> 20. a (7-43)

This is done and images placed. Ready for @julianorrish to check:

`Dropbox (Electric Book Works)\bettercare\courses-professional\intrapartum-care\setting\proofs`

**Comment by julianorrish** [comment]
@arthurattwell: Getting so much better! Hard work paying off.

Figure 3B-4 is smaller in width than the figure above it. Annoying only
because the border highlights this.

Figure 3C-8 is slightly different to the one in the hardcopy I was checking
against, but this version may well be out of date as it is the bigger-sized
book.

Otherwise all good!

On Wed, Feb 25, 2015 at 1:24 PM, Arthur Attwell notifications@github.com
wrote:

> The answers for Test 7 should read as follows: (updated article references)
> 1. b (7-2)
> 2. - 11. are correct
> 12. d (7-18)
> 13. Correct
> 14. a (7-26)
> 15. d (7-33)
> 16. c (7-35)
> 17. b (7-36)
> 18. a (7-38)
> 19. d (7-40)
> 20. a (7-43)
> 
> This is done and images placed. Ready for @julianorrish
> https://github.com/julianorrish to check:
> 
> Dropbox (Electric Book
> Works)\bettercare\courses-professional\intrapartum-care\setting\proofs
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/59#issuecomment-75944738
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
Figure 3B-4: yes, it's a styling issue I haven't been able to resolve. Images that fall inside lists indent with the list. I haven't found a way to override that behaviour yet.

Figure 3C-8: fixed, thanks.

**Comment by arthurattwell** [comment]
New PDF created and checked.
