### ISSUE TITLE
Childhood HIV Corrections_Julia_February

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#60]
(All page numbers refer to new, .md edition)
No disclaimer/block quote box - Missing?
13: Intro: “Updating course material” should be ##
99: After 4-23: “Antiretroviral medication” should be ## instead of a block quote.
142: 5-53: “Every effort must be made…” should be in a block quote
150: 5-71: “TB may present...chest X-ray” should be a continuation of the note above it.

@arthurattwell to implement corrections

**Comment by arthurattwell** [comment]
Done. @julianorrish to check on staging 

http://electricbookworks.github.io/bettercare/childhood-hiv/

and PDF with images placed: `Dropbox (Electric Book Works)\bettercare\courses-professional\childhood-hiv\setting\proofs\20150214_chiv_for-checking.pdf`

**Comment by arthurattwell** [comment]
New PDF at `Dropbox (Electric Book Works)\bettercare\courses-professional\childhood-hiv\setting\proofs`

Closing this issue.
