### ISSUE TITLE
Adult HIV Corrections_Julia_February

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#62]
13: Intro: “Updating course material” should be ##
22: 1-19: “Note:...” should be in note format
42: Chap. 1, Case Study 2, after question 5: “1. What effect is HIV having on society in Africa” - should be a question of it’s own and number 6.
86: 3-30: Last sentence, “Patients need to know about….taking.” should be in a block quote
150: 5-68 last sentence: “Side effects of antiretroviral agents” should be a ## heading
173: 6-30: “note: Mycobacterium...HIV infection” should be in a “Note” format
184: 6-55 last sentence: “note: Tenofovir...used instead” should be in a “Note” format

@arthurattwell to implement

**Comment by arthurattwell** [comment]
Done, ready for @julianorrish to check on staging:

http://electricbookworks.github.io/bettercare/adult-hiv/0-3-contents.html

To check again on PDF once images are in.

**Comment by julianorrish** [comment]
Adult HIV corrections all good @arthurattwell

On Wed, Feb 11, 2015 at 3:48 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #62 https://github.com/electricbookworks/bettercare/issues/62
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/62#event-233925660
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
Great. Over to me for a PDF when the images are in.

**Comment by arthurattwell** [comment]
Image placed, PDF ready for @julianorrish to check: `Dropbox (Electric Book Works)\bettercare\courses-professional\adult-hiv\setting\proofs\20150214_ahiv_for-checking.pdf`

**Comment by julianorrish** [comment]
@arthurattwell Image placement looks perfect.

**Comment by arthurattwell** [comment]
Done!

**Comment by julianorrish** [comment]
Fabulous! :)

On Tuesday, February 24, 2015, Arthur Attwell notifications@github.com
wrote:

> Done!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/62#issuecomment-75762602
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com
