### ISSUE TITLE
Birth Defects Corrections_Julia_February2015

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#63]
13: Intro: “Updating course material” should be ##
220: Test 4, Question 11: “12. Important care...includes:” should be a new question.

@arthurattwell to implement

**Comment by arthurattwell** [comment]
Done, ready for @julianorrish to check on staging:

http://electricbookworks.github.io/bettercare/birth-defects/0-3-contents.html

To check on PDF when images are in.

**Comment by julianorrish** [comment]
All corrected! Now just images to check.

On Wed, Feb 11, 2015 at 3:51 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #63 https://github.com/electricbookworks/bettercare/issues/63
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/63#event-233927364
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
Thanks. I'll create the PDF when the images are in.

**Comment by arthurattwell** [comment]
PDF ready for @julianorrish to check.

`Dropbox (Electric Book Works)\bettercare\courses-professional\birth-defects\setting\proofs`

**Comment by julianorrish** [comment]
@arthurattwell Checking of images done and issues/suggestions noted and
highlighted on the google sheet for images:
https://docs.google.com/a/electricbookworks.com/spreadsheets/d/1kC6kR6ksXvc5NKffANbCQsshcEmRsi_zxbut7x7655A/edit#gid=0

On Mon, Feb 23, 2015 at 9:58 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #63 https://github.com/electricbookworks/bettercare/issues/63
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/63#event-240412349
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
I think this is done. New PDF at `Dropbox (Electric Book Works)\bettercare\courses-professional\birth-defects\setting\proofs`

@julianorrish can you have a last glance before I close?

**Comment by arthurattwell** [comment]
I've improved the photo section layout by making the images smaller. @julianorrish check if you get a chance. Closing the issue -- we can reopen if you find any problems.

**Comment by julianorrish** [comment]
@arthurattwell: looks much better :)

On Wed, Feb 25, 2015 at 6:08 PM, Arthur Attwell notifications@github.com
wrote:

> I've improved the photo section layout by making the images smaller.
> @julianorrish https://github.com/julianorrish check if you get a
> chance. Closing the issue -- we can reopen if you find any problems.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/63#issuecomment-75988488
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com
