### ISSUE TITLE
Breast Care Corrections_Julia_February

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#64]
(All page numbers refer to new, .md edition)
18: Intro: “Updating course material” should be ##
23: 1-5: “Asymmetrical...puberty” should be in a block quote
23: 1-8: “Normal breast anatomy should be ##
78: 4-24: “Painful breasts” (in block quote) should be a ## heading instead
123: 6-33: “Chemotherapy” should be a ## 
127: 6-48: “Targeted therapy” should be a ## 
155: 8-6: “Providing palliative care” should be ## 
158: 8-15: “The management of pain should be ##

@arthurattwell to implement

**Comment by arthurattwell** [comment]
Done, ready for @julianorrish to check on staging:

http://electricbookworks.github.io/bettercare/breast-care/0-3-contents.html

Then to check PDF when images are in.

**Comment by julianorrish** [comment]
All good @arthurattwell.

**Comment by arthurattwell** [comment]
Great, me to do PDFs when images are in.

**Comment by arthurattwell** [comment]
PDF ready for @julianorrish to check.

`Dropbox (Electric Book Works)\bettercare\courses-professional\breast-care\setting\proofs`

**Comment by julianorrish** [comment]
@arthurattwell Checking of images done and issues/suggestions noted on the
google sheet  for images:
https://docs.google.com/a/electricbookworks.com/spreadsheets/d/1kC6kR6ksXvc5NKffANbCQsshcEmRsi_zxbut7x7655A/edit#gid=0

On Mon, Feb 23, 2015 at 5:17 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #64 https://github.com/electricbookworks/bettercare/issues/64
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/64#event-240197037
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com

**Comment by arthurattwell** [comment]
I need to re-size the images here, fixing artboards and label font sizes.

**Comment by arthurattwell** [comment]
I've worked through all these images -- much improved.

@julianorrish can you please check the latest proofs against the original, again, just to check that all images are the correct ones in the right places. I'm worried that during all the reworking something might have broken.

`Dropbox (Electric Book Works)\bettercare\courses-professional\breast-care\setting\proofs\20150227_breast-care.pdf`

**Comment by julianorrish** [comment]
Your worries were unfounded - all images look great.

On Fri, Feb 27, 2015 at 6:02 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #64 https://github.com/electricbookworks/bettercare/issues/64
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/64#event-243357720
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com
