### ISSUE TITLE
Child Healthcare Corrections_Julia_February 2015

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#65]
(All page numbers refer to new, .md edition)
14: Intro: “Updating course material” should be ##
463: Test 9, Question 18: Options missing, should read: a. 1 b. 2 c. 3 d.4 (I checked this on the staging site and it is correct, but in the printed PDF the options are not there)
480: Test 15, Question 8: Same issue as above. The options: a. 15 b. 30 c. 70 d. 90 appear on the staging site but not in the PDF

@arthurattwell  to implement

**Comment by arthurattwell** [comment]
These are done. Next check by @julianorrish only when the images are in and I provide a PDF for checking.

**Comment by arthurattwell** [comment]
Still waiting for images before creating PDF to check.

**Comment by arthurattwell** [comment]
PDF ready for @julianorrish to check.

`Dropbox (Electric Book Works)\bettercare\courses-professional\child-healthcare\setting\proofs`

**Comment by julianorrish** [comment]
@arthurattwell - Images are perfect!

On Thu, Feb 26, 2015 at 7:32 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #65 https://github.com/electricbookworks/bettercare/issues/65
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/65#event-242663988
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com
