### ISSUE TITLE
Primary Newborn Care Corrections_Julia_February 2015

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#66]
(All page numbers refer to new, .md edition)
13: Intro: “Updating course material” should be ##
62: 2-59: “Whenever possible...6 months” should be a block quote

@arthurattwell  to implement

**Comment by arthurattwell** [comment]
Done, over to @julianorrish to check on staging:

http://electricbookworks.github.io/bettercare/primary-newborn-care/0-3-contents.html

And PDF proof with image on Dropbox: `Dropbox (Electric Book Works)\bettercare\courses-professional\primary-newborn-care\proofs\20150214_pnc_for-checking.pdf`

**Comment by julianorrish** [comment]
@arthurattwell Figure placement looks great

On Sat, Feb 14, 2015 at 2:59 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #66 https://github.com/electricbookworks/bettercare/issues/66
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/66#event-235838937
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com
