### ISSUE TITLE
Ebola Prevention and Control Corrections_Julia_February 2015

### ISSUE THREAD

**Issue by julianorrish** [BettercareHealth/bettercare#68]
All page numbers refer to new, .md edition)
13: Intro: “Updating course material” should be ##
60: 3-12: “Wearing gloves...not acceptable”: should be a block quote
97: 4-15: Depends on preference, but in the block quote “microorganisms” could/should be “micro-organisms”?
125: 5-12: “Community education...avoid stigma” should be in a block quote
130: Figure 6-2: Missing final bracket in caption

@arthurattwell to implement

**Comment by arthurattwell** [comment]
Correx done, ready for @julianorrish to check on staging:

http://electricbookworks.github.io/bettercare/ebola-prevention-and-control/0-3-contents.html

**Comment by arthurattwell** [comment]
I'm working on a PDF to check.

**Comment by arthurattwell** [comment]
New PDF ready for @julianorrish to check.

`Dropbox (Electric Book Works)\bettercare\courses-professional\ebola-prevention-and-control\proofs`

**Comment by julianorrish** [comment]
@arthurattwell: Everything looks good - huge improvement on the last
version I saw!

On Wed, Feb 25, 2015 at 4:03 PM, Arthur Attwell notifications@github.com
wrote:

> Assigned #68 https://github.com/electricbookworks/bettercare/issues/68
> to @julianorrish https://github.com/julianorrish.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/electricbookworks/bettercare/issues/68#event-241706161
> .

## 

## 

Kind regards

_Julia Norrish_

Intern | Electric Book Works | 3rd Floor, Sunclare Building, 21 Dreyer
Street, Claremont, Cape Town, 7800 | T: 021 671 1278 | C: +27 (0)74
464 5588 | E:
julia@electricbookworks.com | Website: www.electricbookworks.com
