### ISSUE TITLE
Add FHRH and CHWMBC to home page

### ISSUE THREAD

**Issue by arthurattwell** [BettercareHealth/bettercare#98]
@nkoeries To add these two new books to the home page, so users can read them online, you need to add their linked thumbnails to [`index.md`](https://github.com/BettercareHealth/bettercare/blob/gh-pages/index.md).

To do this

1. Copy an existing entry, e.g.

    ```
    <a href="adult-hiv/0-3-contents.html" title="Adult HIV"><img class="cover-thumb" src="adult-hiv/images/cover-thumb.jpg" alt="Adult HIV" title="Adult HIV is for primary care nurses, medical officers and lay counsellors. It covers management of HIV-infected adults at primary-care clinics, preparing patients for antiretroviral (ARV) treatment, ARV drugs, starting and maintaining patients on ARV treatment and an approach to opportunistic infections." /></a>
    ```
2. Paste that into the relevant spot in the alphabetical order of the books.
3. Edit it replacing all book-specific info with the book you're adding.

**Comment by nkoeries** [comment]
@arthurattwell, thank you. 

1. Title change for CHW-MBC.
2. Update: index.md to include new titles.

Things look reasonable on my fork: https://nkoeries.github.io/bettercare/ 

The final step as far as I can see is uploaded the tests to FileZilla and getting test IDs.

**Comment by arthurattwell** [comment]
Have created #100 for live tests.
